spring:
  datasource:
    username: root
    password: Yto0ver5eas@2018#XATech
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.207.34:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.207.34
    password: XA&Yto0verseas
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000

